[package]
name = "ksni"
version = "0.2.1"
authors = ["iovxw <iovxw@outlook.com>"]
edition = "2018"
description = """
A Rust implementation of the KDE/freedesktop StatusNotifierItem specification
"""
repository = "https://github.com/iovxw/ksni"
keywords = ["systray", "linux", "gui"]
categories = ["api-bindings"]
license = "Unlicense"

[dependencies]
thiserror = "1"
futures = { version = "0.3", default-features = false }
tokio = { version = "1", features = ["rt", "macros"] }
zbus = { version = "3", features = ["tokio"], default-features = false }
serde = { version = "1", features = ["derive"] }
