[package]
name = "ksni"
version = "0.0.0"
authors = ["iovxw <iovxw@outlook.com>"]
edition = "2018"
description = """
A Rust implementation of the KDE/freedesktop StatusNotifierItem specification
"""
repository = "https://github.com/iovxw/ksni"
keywords = ["systray", "linux", "gui"]
categories = ["api-bindings"]
license = "Unlicense"

[badges]
travis-ci = { repository = "iovxw/ksni" }
maintenance = { status = "experimental" }

[dependencies]
#dbus = "^0.7"
dbus = { version = "^0.7", path = "dbus-rs/dbus" }

[build-dependencies]
#dbus-codegen = "^0.4"
dbus-codegen = { version = "^0.4", path = "dbus-rs/dbus-codegen" }
